name: Git Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to build documentation for'
        required: true

jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
    - name: Install sbt
      run: |
        sudo apt-get update
        sudo apt-get install sbt
    - name: Echo tag
      run: echo "The tag is ${{ github.event.inputs.tag }}"
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: master
        submodules: true
    - name: Git version
      run: git version
    - name: pwd
      run: pwd
    - name: ls
      run: ls
